language: ruby
bundler_args: --retry=3 --jobs=3
cache: bundler
sudo: false
rvm:
  - 2.4.2
  - 2.4.1
  - 2.4.0
  - 2.3.5
  - 2.3.4
  - 2.3.3
  - 2.3.2
  - 2.3.1
  - 2.3.0
  - 2.2.8
  - 2.2.7
  - 2.2.6
  - 2.2.5
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
install:
  - bundle install
script:
  - rspec
addons:
  code_climate:
    repo_token: 20981d9b6c53ed895076e87fd8f8d5782800824f86eb501bfccb525dab7deca1
