module AEMO
  module NEM12
    RECORD_INDICATORS = {
      100 => "Header",
      200 => "NMI Data Details",
      300 => "Interval Data",
      400 => "Interval Event",
      500 => "B2B Details",
      900 => "End"
    }

    TRANSACTION_CODE_FLAGS = {
      "A" => "Alteration",
      "C" => "Meter Reconfiguration",
      "G" => "Re-energisation",
      "D" => "De-energisation",
      "E" => "Forward Estimate",
      "N" => "Normal Read",
      "O" => "Other",
      "S" => "Special Read",
      "R" => "Removal of Meter"
    }

    UOM = {
      "MWh"   => { :name => "Megawatt Hour",                 :multiplier => 1e6 },
      "kWh"   => { :name => "Kilowatt Hour",                 :multiplier => 1e3 },
      "Wh"    => { :name => "Watt Hour",                     :multiplier => 1 },
      "MW"    => { :name => "Megawatt",                      :multiplier => 1e6 },
      "kW"    => { :name => "Kilowatt",                      :multiplier => 1e3 },
      "W"     => { :name => "Watt",                          :multiplier => 1 },
      "MVArh" => { :name => "Megavolt Ampere Reactive Hour", :multiplier => 1e6 },
      "kVArh" => { :name => "Kilovolt Ampere Reactive Hour", :multiplier => 1e3 },
      "VArh"  => { :name => "Volt Ampere Reactive Hour",     :multiplier => 1 },
      "MVAr"  => { :name => "Megavolt Ampere Reactive",      :multiplier => 1e6 },
      "kVAr"  => { :name => "Kilovolt Ampere Reactive",      :multiplier => 1e3 },
      "VAr"   => { :name => "Volt Ampere Reactive",          :multiplier => 1 },
      "MVAh"  => { :name => "Megavolt Ampere Hour",          :multiplier => 1e6 },
      "kVAh"  => { :name => "Kilovolt Ampere Hour",          :multiplier => 1e3 },
      "VAh"   => { :name => "Volt Ampere Hour",              :multiplier => 1 },
      "MVA"   => { :name => "Megavolt Ampere",               :multiplier => 1e6 },
      "kVA"   => { :name => "Kilovolt Ampere",               :multiplier => 1e3 },
      "VA"    => { :name => "Volt Ampere",                   :multiplier => 1 },
      "kV"    => { :name => "Kilovolt",                      :multiplier => 1e3 },
      "V"     => { :name => "Volt",                          :multiplier => 1 },
      "kA"    => { :name => "Kiloampere",                    :multiplier => 1e3 },
      "A"     => { :name => "Ampere",                        :multiplier => 1 },
      "pf"    => { :name => "Power Factor",                  :multiplier => 1 }
    }

    QUALITY_FLAGS = {
      "A" => "Actual Data",
      "E" => "Forward Estimated Data",
      "F" => "Final Substituted Data",
      "N" => "Null Data",
      "S" => "Substituted Data",
      "V" => "Variable Data",
    }

    METHOD_FLAGS = {
      "11" => { type: ["SUB"],        installation_type: [1, 2, 3, 4], short_descriptor: "Check",                        description: "" },
      "12" => { type: ["SUB"],        installation_type: [1, 2, 3, 4], short_descriptor: "Calculated",                   description: "" },
      "13" => { type: ["SUB"],        installation_type: [1, 2, 3, 4], short_descriptor: "SCADA",                        description: "" },
      "14" => { type: ["SUB"],        installation_type: [1, 2, 3, 4], short_descriptor: "Like Day",                     description: "" },
      "15" => { type: ["SUB"],        installation_type: [1, 2, 3, 4], short_descriptor: "Average Like Day",             description: "" },
      "16" => { type: ["SUB"],        installation_type: [1, 2, 3, 4], short_descriptor: "Agreed",                       description: "" },
      "17" => { type: ["SUB"],        installation_type: [1, 2, 3, 4], short_descriptor: "Linear",                       description: "" },
      "18" => { type: ["SUB"],        installation_type: [1, 2, 3, 4], short_descriptor: "Alternate",                    description: "" },
      "19" => { type: ["SUB"],        installation_type: [1, 2, 3, 4], short_descriptor: "Zero",                         description: "" },
      "51" => { type: ["EST", "SUB"], installation_type: 5,            short_descriptor: "Previous Year",                description: "" },
      "52" => { type: ["EST", "SUB"], installation_type: 5,            short_descriptor: "Previous Read",                description: "" },
      "53" => { type: ["SUB"],        installation_type: 5,            short_descriptor: "Revision",                     description: "" },
      "54" => { type: ["SUB"],        installation_type: 5,            short_descriptor: "Linear",                       description: "" },
      "55" => { type: ["SUB"],        installation_type: 5,            short_descriptor: "Agreed",                       description: "" },
      "56" => { type: ["EST", "SUB"], installation_type: 5,            short_descriptor: "Prior to First Read – Agreed", description: "" },
      "57" => { type: ["EST", "SUB"], installation_type: 5,            short_descriptor: "Customer Class",               description: "" },
      "58" => { type: ["EST", "SUB"], installation_type: 5,            short_descriptor: "Zero",                         description: "" },
      "61" => { type: ["EST", "SUB"], installation_type: 6,            short_descriptor: "Previous Year",                description: "" },
      "62" => { type: ["EST", "SUB"], installation_type: 6,            short_descriptor: "Previous Read",                description: "" },
      "63" => { type: ["EST", "SUB"], installation_type: 6,            short_descriptor: "Customer Class",               description: "" },
      "64" => { type: ["SUB"],        installation_type: 6,            short_descriptor: "Agreed",                       description: "" },
      "65" => { type: ["EST"],        installation_type: 6,            short_descriptor: "ADL",                          description: "" },
      "66" => { type: ["SUB"],        installation_type: 6,            short_descriptor: "Revision",                     description: "" },
      "67" => { type: ["SUB"],        installation_type: 6,            short_descriptor: "Customer Read",                description: "" },
      "68" => { type: ["EST", "SUB"], installation_type: 6,            short_descriptor: "Zero",                         description: "" },
      "71" => { type: ["SUB"],        installation_type: 7,            short_descriptor: "Recalculation",                description: "" },
      "72" => { type: ["SUB"],        installation_type: 7,            short_descriptor: "Revised Table",                description: "" },
      "73" => { type: ["SUB"],        installation_type: 7,            short_descriptor: "Revised Algorithm",            description: "" },
      "74" => { type: ["SUB"],        installation_type: 7,            short_descriptor: "Agreed",                       description: "" },
      "75" => { type: ["EST"],        installation_type: 7,            short_descriptor: "Existing Table",               description: "" }
    }

    REASON_CODES = {
      0  => "Free Text Description",
      1  => "Meter/Equipment Changed",
      2  => "Extreme Weather/Wet",
      3  => "Quarantine",
      4  => "Savage Dog",
      5  => "Meter/Equipment Changed",
      6  => "Extreme Weather/Wet",
      7  => "Unable To Locate Meter",
      8  => "Vacant Premise",
      9  => "Meter/Equipment Changed",
      10 => "Lock Damaged/Seized",
      11 => "In Wrong Walk",
      12 => "Locked Premises",
      13 => "Locked Gate",
      14 => "Locked Meter Box",
      15 => "Access - Overgrown",
      16 => "Noxious Weeds",
      17 => "Unsafe Equipment/Location",
      18 => "Read Below Previous",
      19 => "Consumer Wanted",
      20 => "Damaged Equipment/Panel",
      21 => "Switched Off",
      22 => "Meter/Equipment Seals Missing",
      23 => "Meter/Equipment Seals Missing",
      24 => "Meter/Equipment Seals Missing",
      25 => "Meter/Equipment Seals Missing",
      26 => "Meter/Equipment Seals Missing",
      27 => "Meter/Equipment Seals Missing",
      28 => "Damaged Equipment/Panel",
      29 => "Relay Faulty/Damaged",
      30 => "Meter Stop Switch On",
      31 => "Meter/Equipment Seals Missing",
      32 => "Damaged Equipment/Panel",
      33 => "Relay Faulty/Damaged",
      34 => "Meter Not In Handheld",
      35 => "Timeswitch Faulty/Reset Required",
      36 => "Meter High/Ladder Required",
      37 => "Meter High/Ladder Required",
      38 => "Unsafe Equipment/Location",
      39 => "Reverse Energy Observed",
      40 => "Timeswitch Faulty/Reset Required",
      41 => "Faulty Equipment Display/Dials",
      42 => "Faulty Equipment Display/Dials",
      43 => "Power Outage",
      44 => "Unsafe Equipment/Location",
      45 => "Readings Failed To Validate",
      46 => "Extreme Weather/Hot",
      47 => "Refused Access",
      48 => "Timeswitch Faulty/Reset Required",
      49 => "Wet Paint",
      50 => "Wrong Tariff",
      51 => "Installation Demolished",
      52 => "Access - Blocked",
      53 => "Bees/Wasp In Meter Box",
      54 => "Meter Box Damaged/Faulty",
      55 => "Faulty Equipment Display/Dials",
      56 => "Meter Box Damaged/Faulty",
      57 => "Timeswitch Faulty/Reset Required",
      58 => "Meter Ok - Supply Failure",
      59 => "Faulty Equipment Display/Dials",
      60 => "Illegal Connection/Equipment Tampered",
      61 => "Meter Box Damaged/Faulty",
      62 => "Damaged Equipment/Panel",
      63 => "Illegal Connection/Equipment Tampered",
      64 => "Key Required",
      65 => "Wrong Key Provided",
      66 => "Lock Damaged/Seized",
      67 => "Extreme Weather/Wet",
      68 => "Zero Consumption",
      69 => "Reading Exceeds Estimate",
      70 => "Probe Reports Tampering",
      71 => "Probe Read Error",
      72 => "Meter/Equipment Changed",
      73 => "Low Consumption",
      74 => "High Consumption",
      75 => "Customer Read",
      76 => "Communications Fault",
      77 => "Estimation Forecast",
      78 => "Null Data",
      79 => "Power Outage Alarm",
      80 => "Short Interval Alarm",
      81 => "Long Interval Alarm",
      82 => "CRC Error",
      83 => "RAM Checksum Error",
      84 => "ROM Checksum Error",
      85 => "Data Missing Alarm",
      86 => "Clock Error Alarm",
      87 => "Reset Occurred",
      88 => "Watchdog Timeout Alarm",
      89 => "Time Reset Occurred",
      90 => "Test Mode",
      91 => "Load Control",
      92 => "Added Interval (Data Correction)",
      93 => "Replaced Interval (Data Correction)",
      94 => "Estimated Interval (Data Correction)",
      95 => "Pulse Overflow Alarm",
      96 => "Data Out Of Limits",
      97 => "Excluded Data",
      98 => "Parity Error",
      99 => "Energy Type (Register Changed)"
    }

    DATA_STREAM_SUFFIX = {
      # Averaged Data Streams
      "A" => { :stream => "Average", :description => "Import",                      :units => "kWh" },
      "D" => { :stream => "Average", :description => "Export",                      :units => "kWh" },
      "J" => { :stream => "Average", :description => "Import",                      :units => "kVArh" },
      "P" => { :stream => "Average", :description => "Export",                      :units => "kVArh" },
      "S" => { :stream => "Average", :description => "",                            :units => "kVAh" },
      # Master Data Streams
      "B" => { :stream => "Master",  :description => "Import",                      :units => "kWh" },
      "E" => { :stream => "Master",  :description => "Export",                      :units => "kWh" },
      "K" => { :stream => "Master",  :description => "Import",                      :units => "kVArh" },
      "Q" => { :stream => "Master",  :description => "Export",                      :units => "kVArh" },
      "T" => { :stream => "Master",  :description => "",                            :units => "kVAh" },
      "G" => { :stream => "Master",  :description => "Power Factor",                :units => "PF" },
      "H" => { :stream => "Master",  :description => "Q Metering",                  :units => "Qh" },
      "M" => { :stream => "Master",  :description => "Par Metering",                :units => "parh" },
      "V" => { :stream => "Master",  :description => "Volts or V2h or Amps or A2h", :units => "" },
      # Check Meter Streams
      "C" => { :stream => "Check",   :description => "Import",                      :units => "kWh" },
      "F" => { :stream => "Check",   :description => "Export",                      :units => "kWh" },
      "L" => { :stream => "Check",   :description => "Import",                      :units => "kVArh" },
      "R" => { :stream => "Check",   :description => "Export",                      :units => "kVArh" },
      "U" => { :stream => "Check",   :description => "",                            :units => "kVAh" },
      "Y" => { :stream => "Check",   :description => "Q Metering",                  :units => "Qh" },
      "W" => { :stream => "Check",   :description => "Par Metering Path",           :units => "" },
      "Z" => { :stream => "Check",   :description => "Volts or V2h or Amps or A2h", :units => "" },
      # Net Meter Streams
      "D" => { :stream => "Net",     :description => "Net",                         :units => "kWh" },
      "J" => { :stream => "Net",     :description => "Net",                         :units => "kVArh" }
    }
  end
end
