---
name: Lints
on:
  pull_request:
  push:
    tags-ignore:
    - '*'
    paths-ignore:
    - '*.md'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run lints
      run: bundle exec rubocop
