---
name: Test + lint
on:
  pull_request:
  push:
    tags-ignore:
    - '*'
    paths-ignore:
    - '*.md'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run lints
      run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2']
        experimental: [false]
        include:
          - ruby-version: 'head'
            experimental: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      env:
        COVERALLS_REPO_TOKEN: ${{ sescrets.COVERALLS_REPO_TOKEN }}
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: bundle exec rspec
